services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${HOST}"
      - "traefik.port=3000"
      - "traefik.protocol=http"
      - "traefik.docker.network=app-network"
    networks:
      - app-network

  docker-proxy:
    image: docker:27-dind
    container_name: docker-proxy
    restart: always
    privileged: true
    command: ["socat", "-v", "TCP-LISTEN:2375,fork,reuseaddr", "UNIX-CONNECT:/var/run/docker.sock"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  traefik:
    image: "traefik:v1.7"
    container_name: "traefik"
    restart: always
    command:
      - "--api"
      - "--api.dashboard=true"
      - "--docker=true"
      - "--docker.exposedbydefault=false"
      - "--docker.watch=true"
      - "--docker.endpoint=tcp://docker-proxy:2375"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--acme.email=${EMAIL}"
      - "--acme.storage=/letsencrypt/acme.json"
      - "--acme.entrypoint=https"
      - "--acme.httpchallenge=true"
      - "--acme.httpchallenge.entrypoint=http"
      - "--acme.onhostrule=true"
      - "--logLevel=DEBUG"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
